version: '3.8'

services:
  api:
    build: ./api_server
    container_name: cosplay_api
    restart: unless-stopped
    environment:
      - DATABASE_URL=sqlite:////app/db.sqlite3
      - SD_SERVER_URL=http://sd_server:8188
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./api_server/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    depends_on:
      - sd_server

  telegram_bot:
    build: ./telegram_bot
    container_name: cosplay_bot
    restart: unless-stopped
    environment:
      - API_URL=http://api:8000
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    depends_on:
      - api

  sd_server:
    build: ./sd_server
    container_name: cosplay_sd
    restart: unless-stopped
    ports:
      - "8188:8188"
    volumes:
      - ./sd_server/models:/app/models
      - ./sd_server/outputs:/app/outputs
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  nginx:
    image: nginx:alpine
    container_name: cosplay_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - api
      - sd_server